[tool.poetry]
name = "cliboa"
version = "1.0"
description = ""
authors = ["Tomoki Maeda"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
boto3 = "==1.20.16"
requests = "==2.26.0"
cloudpickle = "==2.0.0"
configparser = "==5.1.0"
PyMySQL = "==1.0.2"
mock = "==4.0.3"
multiprocessing-logging = "==0.3.1"
paramiko = "==2.10.1"
chardet = "==4.0.0"
jsonlines = "==2.0.0"
feedparser = "==6.0.8"
xlrd = "==1.2.0"
pandas = "==1.3.4"
google-auth = ">=2.3.3"
google-cloud-storage = "==1.43.0"
google-cloud-bigquery = "==2.30.1"
google-cloud-firestore = "==2.3.4"
pandas-gbq = "==0.16.0"
PyYaml = "==6.0"
azure-storage-blob = "==12.9.0"
python-gnupg = "==0.4.8"
openpyxl = "==3.0.9"
pyminizip = "==0.2.5"
psycopg2 = "==2.9.1"
numpy = "<2"

[tool.poetry.dev-dependencies]
autoflake = "==1.3.1"
black = "==22.3.0"
flake8 = "==3.7.9"
import-linter = "==1.2.7"
isort = "==4.3.21"
pycodestyle = "==2.5.0"
pytest = "==5.0.1"
pytest-cov = "==2.10.0"
XlsxWriter = "==1.1.8"
safety = "==1.9.0"

[tool.black]
line-length = 100
target-version = ["py37"]

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = "0"
indent = '    '
multi_line_output = "3"
length_sort = "0"
line_length = "100"
include_trailing_comma = true
profile = "black"
use_parentheses = true

[tool.flake8]
max-line-length = 100